version: '3.8'

services:
  # Frontend Development Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api
      - mongodb
      - redis

  # API Backend (Future Implementation)
  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mathverse
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mongodb
      - redis
    command: sh -c "npm install && npm run dev"

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mathverse
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # AI/ML Service (Future Implementation)
  ml-service:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./ml-backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - MONGODB_URI=mongodb://mongodb:27017/mathverse
    depends_on:
      - mongodb
    command: sh -c "pip install -r requirements.txt && python main.py"

volumes:
  mongodb_data:
  redis_data:
